export const MUPI_MODEL_DESCRIPTION = 'MUPI_MODEL_DESCRIPTION';
export const MUPI_MODEL_TITLE = 'MUPI_MODEL_TITLE';
export const MUPI_MODEL_IF_UPLOAD = 'MUPI_MODEL_IF_UPLOAD';
export const MUPI_MODEL_ITEM_ID = 'MUPI_MODEL_ITEM_ID';
export const MUPI_MODEL_ITEM_IF_LISTED = 'MUPI_MODEL_ITEM_IF_LISTED';
